CREATE DATABASE IF NOT EXISTS Clase2;

USE Clase2;

CREATE TABLE IF NOT EXISTS regiones(
	IDREG INT AUTO_INCREMENT,
    NOMREG VARCHAR(20) NOT NULL,
    
    CONSTRAINT pk_regiones PRIMARY KEY (IDREG)
);

CREATE TABLE IF NOT EXISTS formapago(
	IDFORMA INT AUTO_INCREMENT,
	DETALLE VARCHAR(18),
	
	CONSTRAINT pk_formapago PRIMARY KEY (IDFORMA)
);

CREATE TABLE IF NOT EXISTS ciudades(
	IDCIU INT AUTO_INCREMENT,
	NOMCIU VARCHAR(20),
	FKIDREG INT,
	
	CONSTRAINT pk_ciudad PRIMARY KEY (IDCIU),
	CONSTRAINT fk_formapago_regiones FOREIGN KEY (FKIDREG) REFERENCES regiones(IDREG)
	
);

CREATE TABLE IF NOT EXISTS servicios(
	IDSER INT AUTO_INCREMENT,
	NOMSER VARCHAR(20),
	VALORMES INT,
	
	CONSTRAINT pk_servicios PRIMARY KEY (IDSER)
);

CREATE TABLE IF NOT EXISTS clientes(
	IDRUT INT AUTO_INCREMENT,
	APEPAT VARCHAR(20),
	APEMAT VARCHAR(20),
	NOMBRES VARCHAR(25),
	DIRECC VARCHAR(30),
	FKIDCIU INT,
	
	CONSTRAINT pk_clientes PRIMARY KEY (IDRUT),
	CONSTRAINT pk_clientes_ciudades FOREIGN KEY (FKIDCIU) REFERENCES ciudades(IDCIU)
);

CREATE TABLE IF NOT EXISTS pagos(
	IDPAGO INT AUTO_INCREMENT,
	FECHA DATE,
	TOTAL INT,
	FKIDRUT INT,
	FKIDFORMA INT,
	FKIDSER INT,
	
	CONSTRAINT pk_pagos PRIMARY KEY (IDPAGO),
	CONSTRAINT fk_pagos_clientes FOREIGN KEY (FKIDRUT) REFERENCES clientes(IDRUT),
	CONSTRAINT fk_pagos_formapago FOREIGN KEY (FKIDFORMA) REFERENCES formapago(IDFORMA),
	CONSTRAINT fk_pago_servicios FOREIGN KEY (FKIDSER) REFERENCES servicios(IDSER)
);