CREATE USER 'cid'@'localhost' IDENTIFIED BY '1234';

CREATE DATABASE bd_cid;

GRANT ALL PRIVILEGES ON bd_cid.* TO 'cid'@'localhost';
FLUSH PRIVILEGES;

SELECT User, Host FROM mysql.user WHERE User = 'cid';

CREATE TABLE IF NOT EXISTS regiones(
	IDREG INT,
    NOMREG VARCHAR(20) NOT NULL,
    
    CONSTRAINT pk_regiones PRIMARY KEY (IDREG)
);

CREATE TABLE IF NOT EXISTS formapago(
	IDFORMA INT,
	DETALLE VARCHAR(18),
	
	CONSTRAINT pk_formapago PRIMARY KEY (IDFORMA)
);

CREATE TABLE IF NOT EXISTS servicios(
	IDSER INT,
	NOMSER VARCHAR(20),
	VALORMES INT,
	
	CONSTRAINT pk_servicios PRIMARY KEY (IDSER)
);

CREATE TABLE IF NOT EXISTS ciudades(
	IDCIU INT,
	NOMCIU VARCHAR(20),
	FKIDREG INT,
	
	CONSTRAINT pk_ciudad PRIMARY KEY (IDCIU),
	CONSTRAINT fk_ciudades_regiones FOREIGN KEY (FKIDREG) REFERENCES regiones(IDREG)
);

CREATE TABLE IF NOT EXISTS tipocliente(
	IDTIPO INT,
	DESCRIPCION VARCHAR(20),
	
	CONSTRAINT pk_tipocliente PRIMARY KEY (IDTIPO)
);

CREATE TABLE IF NOT EXISTS clientes(
	IDRUT INT,
	APEPAT VARCHAR(20),
	APEMAT VARCHAR(20),
	NOMBRES VARCHAR(25),
	DIRECC VARCHAR(30),
	FKIDCIU INT,
	FKIDTIPO INT,
	
	CONSTRAINT pk_clientes PRIMARY KEY (IDRUT),
	CONSTRAINT fk_clientes_ciudades FOREIGN KEY (FKIDCIU) REFERENCES ciudades(IDCIU),
	CONSTRAINT fk_clientes_tipocliente FOREIGN KEY (FKIDTIPO) REFERENCES tipocliente(IDTIPO)
);

CREATE TABLE IF NOT EXISTS pagos(
	IDPAGO INT,
	FECHA DATE,
	TOTAL INT,
	FKIDRUT INT,
	FKIDFORMA INT,
	FKIDSER INT,
	
	CONSTRAINT pk_pagos PRIMARY KEY (IDPAGO),
	CONSTRAINT fk_pagos_clientes FOREIGN KEY (FKIDRUT) REFERENCES clientes(IDRUT),
	CONSTRAINT fk_pagos_formapago FOREIGN KEY (FKIDFORMA) REFERENCES formapago(IDFORMA),
	CONSTRAINT fk_pago_servicios FOREIGN KEY (FKIDSER) REFERENCES servicios(IDSER)
);

SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA = 'bd_cid';

CREATE SEQUENCE seq_regiones START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_formapago START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_servicios START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_ciudades START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_tipocliente START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_clientes START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_pagos START WITH 1 INCREMENT BY 1;

SELECT TABLE_NAME, TABLE_TYPE FROM information_schema.TABLES 
WHERE TABLE_SCHEMA = 'bd_cid' AND TABLE_TYPE = 'SEQUENCE';